// Maps this app's LANGUAGES list (src/i18n/languages.ts, mostly ISO 639-1)
// to the language codes used by bible.helloao.org's /available_translations.json
// (ISO 639-3, e.g. 'swh' for Swahili, not the macrolanguage code 'sw').
// Every entry here was verified against a live snapshot of that endpoint
// ({len(items)} translations / {len(available)} languages as of this writing) --
// see services/bibleLibrary.ts for how this is used. A code with no entry
// here just means this particular API doesn't have a Bible in that
// language yet -- the library screen still works, it just won't show a
// "your language" highlight for that one.
export const APP_LANG_TO_BIBLE_API_LANG: Record<string, string> = {
  en: 'eng',
  es: 'spa',
  zh: 'cmn',
  hi: 'hin',
  ar: 'arb',
  pt: 'por',
  bn: 'ben',
  ru: 'rus',
  ja: 'jpn',
  pa: 'pan',
  de: 'deu',
  jv: 'jvn',
  ko: 'kor',
  fr: 'fra',
  te: 'tel',
  mr: 'mar',
  tr: 'tur',
  ta: 'tam',
  vi: 'vie',
  ur: 'urd',
  it: 'ita',
  gu: 'guj',
  pl: 'pol',
  uk: 'ukr',
  fa: 'pes',
  ml: 'mal',
  kn: 'kan',
  my: 'mya',
  th: 'tha',
  or: 'ory',
  am: 'amh',
  nl: 'nld',
  yo: 'yor',
  ig: 'ibo',
  ha: 'hau',
  sw: 'swh',
  so: 'som',
  sn: 'sna',
  ny: 'nya',
  ne: 'npi',
  ku: 'ckb',
  ro: 'ron',
  // NOTE: modern Greek ('ell') isn't in this API's language set -- only
  // 'grc' (Ancient/Koine Greek, the New Testament's original language)
  // is available. Deliberately NOT mapped here: presenting Ancient Greek
  // as "your language: Greek" would mislead a modern Greek speaker.
  // Ancient Greek texts are still browsable in the full translation list.
  cs: 'ces',
  sv: 'swe',
  hu: 'hun',
  he: 'heb',
  be: 'bel',
  tg: 'tgk',
  srp: 'srp',
  da: 'dan',
  fi: 'fin',
  sk: 'slk',
  no: 'nob',
  hr: 'hrv',
  lt: 'lit',
  et: 'ekk',
  is: 'isl',
  id: 'ind',
  ms: 'zlm',
  tl: 'tgl',
  as: 'asm',
  sa: 'san',
  lug: 'lug',
  twi: 'twi',
  wo: 'wol',
  ff: 'fuf',
  om: 'gaz',
  mg: 'tdx',
  ht: 'hat',
  yi: 'ydd',
  ceb: 'ceb',
  ug: 'uig',
  bo: 'bod',
  to: 'ton',
};
