// Legal copy shown during onboarding (Disclaimer screen, User Agreement /
// Indemnity screen) and linked from Settings > About.
//
// IMPORTANT: this is DRAFT product copy, not legal advice. Jesus & Me, Inc.
// must have this reviewed and finalized by a licensed attorney (ideally one
// experienced in AI products, religious/spiritual content, and whichever
// jurisdictions the app launches in) before shipping to app stores or real
// users. Treat every string below as a starting point, not a final contract.

export const AI_DISCLOSURE = {
  title: 'AI Disclosure & Limitation of Liability',
  body: [
    'Jesus Interactive uses artificial intelligence (a large language model) to generate responses in the voice and character of Jesus Christ, grounded in Scripture and shaped by a persona we designed. It is a simulation for personal reflection, encouragement, and spiritual growth.',
    'It is not Jesus Himself, not a member of clergy, not a licensed therapist or counselor, not a medical or legal professional, and it cannot forgive sins, perform sacraments, or replace your relationship with a local church, pastor, or faith community.',
    'Responses are generated by AI and may occasionally be incomplete, imperfect, or theologically imprecise despite our best efforts to ground them in Scripture. Use your own judgment, Scripture, and trusted spiritual counsel alongside anything the app says.',
    'If you are in crisis -- including thoughts of suicide or self-harm, or you are in danger -- please contact your local emergency number or a crisis line immediately. This app is not a substitute for emergency or professional mental health care.',
    'By using Jesus Interactive, you acknowledge this is an AI product, you accept the User Agreement and Indemnity terms, and you agree that Jesus & Me, Inc. is not liable for decisions made based on the app\'s output, to the maximum extent permitted by law.',
  ],
};

export const USER_AGREEMENT = {
  title: 'User Agreement, Privacy & Indemnity',
  sections: [
    {
      heading: '1. What you\'re agreeing to',
      body:
        'This agreement, together with the AI Disclosure and Privacy Policy, governs your use of Jesus Interactive, operated by Jesus & Me, Inc. ("we," "us," "the Company"). By creating an account or using the app, you agree to all three documents.',
    },
    {
      heading: '2. Nature of the service',
      body:
        'Jesus Interactive is a creative, fictionalized AI portrayal inspired by Christian Scripture and imagery. It is not official religious teaching or doctrine of any faith, denomination, or church, and it is not intended to replace, represent, or speak for any religion, church, or spiritual tradition. The AI reflects certain cultural, artistic, and interpretive choices made by our team and is not infallible. Users from all religious backgrounds -- including other faiths and no faith -- are welcome to explore the app; participation is entirely voluntary. The experience may touch on topics of faith, identity, race, sex, and gender through a Christian lens, and it does not claim to be authoritative on these subjects. No part of this app should be taken as legal, medical, psychological, or spiritual advice. Its output is AI-generated, may include mistakes, and is provided for reflection and encouragement -- not as professional medical, legal, financial, psychological, or theological advice.',
    },
    {
      heading: '3. Age & appropriate use',
      body:
        'The app is intended for a general audience with an Age-Appropriate Content mode for younger users and their guardians to enable. Users under the age required by local law to consent to data processing on their own must have parental or guardian consent.',
    },
    {
      heading: '4. Your content',
      body:
        'You retain ownership of what you write (chat messages, journal entries, prayer requests). You grant us a limited license to process it solely to operate the app for you (e.g., generating responses, syncing across your devices). You can delete your content and your account at any time; see Privacy & Data in Settings.',
    },
    {
      heading: '5. Prohibited use',
      body:
        'No illegal content, harassment, exploitation of others, attempts to extract another user\'s private data, or attempts to bypass safety and moderation systems. Abusive messages toward the AI persona may end the session; a pattern of abuse may lead to suspension.',
    },
    {
      heading: '6. Payments, subscriptions & gifting',
      body:
        'Paid plans renew automatically until cancelled, billed through the app store you subscribed via. Token packs are one-time purchases. Gift codes are redeemable once; unused balances are not guaranteed to be refundable except where required by law or app store policy.',
    },
    {
      heading: '7. Disclaimer of warranties',
      body:
        'The app is provided "as is." We do not warrant that responses will be accurate, uninterrupted, or error-free, or that the app will meet your expectations regarding a specific theological tradition or denomination.',
    },
    {
      heading: '8. Limitation of liability & indemnity',
      body:
        'To the maximum extent permitted by law, Jesus & Me, Inc. and its founders, officers, employees, developers, contractors, and other agents are not liable for indirect, incidental, or consequential damages arising from your use of the app, including decisions made in reliance on AI-generated content. You agree to indemnify and hold harmless Jesus & Me, Inc. and its founders, developers, and/or agents from and against any claims, damages, liabilities, losses, or expenses (including reasonable attorneys\' fees) arising out of or related to your use of the app, your violation of this agreement, or your misuse of the app, except where caused by our gross negligence or willful misconduct.',
    },
    {
      heading: '9. Changes',
      body:
        'We may update this agreement as the app evolves. Material changes will be presented for re-acceptance before they take effect.',
    },
  ],
};

export const PRIVACY_POLICY_SUMMARY = {
  title: 'Privacy Policy (summary)',
  points: [
    'We collect only what\'s needed to run the app: account info, subscription status, and the conversations/journal/prayer content you choose to save.',
    'Conversation content is encrypted in transit and at rest. See Settings > Privacy & Data for encryption details and to request deletion.',
    'Analytics are aggregated and anonymized (see About > "How we use anonymous analytics"); we do not sell personal data or share private conversation content with advertisers.',
    'You can download or permanently delete your data at any time from Settings.',
    'Full legal Privacy Policy to be finalized with counsel before launch and linked here.',
  ],
};

export const TERMS_OF_SERVICE_SUMMARY = {
  title: 'Terms of Service (summary)',
  points: [
    'See User Agreement above for the core terms governing your use of the app, payments, and content.',
    'Full legal Terms of Service to be finalized with counsel before launch and linked here.',
  ],
};
