// Legal copy shown during onboarding (Disclaimer screen, User Agreement
// screen) and linked from Settings. Finalized text provided by the app
// owner (August 16, 2026). The Apple/Google developer account is
// enrolled as an individual (Alizabeth James), not a formed company, so
// the legal documents name her as the actual contracting party, doing
// business as "Jesus Interactive" -- the brand/app name used everywhere
// else (persona, UI, App Store listing name) is unaffected.

export const AI_DISCLOSURE = {
  title: 'AI Disclosure & User Acknowledgment',
  lastUpdated: 'August 16, 2026',
  intro:
    'Jesus Interactive is operated by Alizabeth James, an individual doing business as Jesus Interactive ("we," "us," "our," or "Jesus Interactive"). Jesus Interactive uses artificial intelligence to generate conversational responses, sermon drafts, reflections, and other content. This Disclosure explains the nature of that technology, its limitations, and the legal agreement you accept by using the AI features.\n\nBy tapping "I Understand and Agree," creating an account, or continuing to use any AI-powered feature of the App, you acknowledge that you have read, understood, and agree to every part of this AI Disclosure and User Acknowledgment.',
  sections: [
    {
      heading: '1. Nature of the AI',
      body:
        'The responses you receive in the chat, Sermon Writer, and related features are generated by artificial intelligence models operated by third-party providers.\n\nThe AI is not Jesus Christ. The AI is not a real person. The AI is not divine, does not possess spiritual authority, and does not receive or transmit revelation from God.\n\nThe AI has been instructed to respond in a style inspired by the words and teachings of Jesus as recorded in the Christian Scriptures. This is a literary and educational simulation only. It is not a channel of communication with the living Christ, the Holy Spirit, or any spiritual being.',
    },
    {
      heading: '2. What the AI Can and Cannot Do',
      body:
        'The AI may:\n- Generate responses in a conversational style consistent with biblical themes\n- Reference or paraphrase Scripture (when properly configured)\n- Help draft sermon outlines, reflections, or study notes\n- Provide general encouragement drawn from Christian teachings\n\nThe AI cannot and does not:\n- Speak with divine authority or as God\n- Provide new revelation, prophecy, or personal messages from God\n- Replace the Bible, prayer, worship, or the local church\n- Offer pastoral counseling, spiritual direction, or sacramental ministry\n- Diagnose, treat, or advise on medical, mental-health, legal, or financial matters\n- Guarantee biblical accuracy on every response (AI systems can err, invent details, or misapply Scripture)',
    },
    {
      heading: '3. Potential for Error and "Hallucinations"',
      body:
        'Artificial intelligence systems sometimes produce inaccurate, incomplete, or fabricated information (commonly called "hallucinations"). This includes the possibility of:\n- Incorrect or non-existent Bible references\n- Theological statements that conflict with historic Christian orthodoxy\n- Invented personal details or stories presented as fact\n- Biased or incomplete interpretations of Scripture\n\nYou are solely responsible for verifying any biblical quotation, theological claim, or advice against the actual text of Scripture and the teaching of your church or pastor.',
    },
    {
      heading: '4. Not a Substitute for Real Spiritual Care',
      body:
        'Jesus Interactive is an educational and reflective tool only. It is not a substitute for:\n- Reading and studying the Bible itself\n- Personal prayer and worship\n- Participation in a local church community\n- Guidance from ordained pastors, priests, elders, or qualified spiritual directors\n- Professional mental-health, medical, or crisis counseling\n\nIf you are experiencing emotional distress, thoughts of self-harm, or a spiritual crisis, please contact a trusted pastor, counselor, or emergency services immediately. In the United States you may call or text 988 (Suicide & Crisis Lifeline).',
    },
    {
      heading: '5. Data Sent to AI Providers',
      body:
        'When you use AI features, the text of your messages (and limited conversation history needed for context) is transmitted to one or more third-party AI providers so that a response can be generated.\n\nBy using the AI features you explicitly consent to this transmission. We do not sell your chat content. We do not use your private conversations to train third-party foundation models unless you give separate, explicit opt-in consent (which is not required to use the Service).\n\nFurther details are set out in our Privacy Policy.',
    },
    {
      heading: '6. Labeling of AI Content',
      body:
        'All AI-generated responses within the App are marked or presented in a manner that indicates they are produced by artificial intelligence. You will also see periodic reminders of this Disclosure.',
    },
    {
      heading: '7. Reporting and Moderation',
      body:
        'The App includes in-app reporting and flagging tools. If you encounter content that is offensive, inaccurate, theologically problematic, or otherwise inappropriate, please use the report feature. We review reports and may remove or restrict content or accounts that violate our Terms of Service.',
    },
    {
      heading: '8. Indemnity and Release (User Acknowledgment)',
      body:
        'By using the AI features of Jesus Interactive, you agree to the following:\n\n1. You understand and accept that all AI-generated content is a simulation only and is not the voice, words, or authority of Jesus Christ, God, or any divine being.\n\n2. You agree that you will not treat any AI response as divine revelation, prophecy, personal guidance from God, or a substitute for Scripture, prayer, pastoral care, or professional advice.\n\n3. You assume full responsibility for any decisions, actions, beliefs, or consequences that result from your use of or reliance on AI-generated content.\n\n4. To the maximum extent permitted by law, you release, waive, and forever discharge Jesus Interactive and its agents, successors, and assigns from any and all claims, demands, damages, losses, liabilities, costs, and expenses (including reasonable attorneys\' fees) arising out of or related to: your use of the AI features; any AI-generated content; any reliance you place on that content; and any emotional, spiritual, psychological, financial, or other harm you claim resulted from the AI.\n\n5. You agree to indemnify, defend, and hold harmless Jesus Interactive from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys\' fees) brought by you or any third party arising out of or related to your use of the AI features or your breach of this Acknowledgment.\n\n6. This indemnity and release is intended to be as broad and inclusive as permitted under the laws of the State of California and shall survive the termination of your use of the App.',
    },
    {
      heading: '9. Changes to This Disclosure',
      body:
        'We may update this AI Disclosure & User Acknowledgment from time to time. The "Last Updated" date at the top will reflect the most recent revision. Continued use of the AI features after changes constitutes acceptance of the revised version.',
    },
    {
      heading: '10. Contact',
      body:
        'If you have questions about this AI Disclosure or the AI features of Jesus Interactive, please contact us at:\n\nAlizabeth James, doing business as Jesus Interactive\nEmail: Ajames@jesusinteractive.com\nCathedral City, California, United States\n© 2026 Jesus Interactive',
    },
  ],
  closing:
    'By tapping "I understand and agree" or by continuing to use the AI features, you confirm that you have read this entire document, understand it, and agree to be legally bound by it, including the indemnity and release in Section 8.',
};

// Onboarding's UserAgreementScreen.tsx and Settings both render this as
// the full Terms of Service -- kept under the existing export name
// (USER_AGREEMENT) so neither screen needed to change which constant
// they import; only the content and title changed.
export const USER_AGREEMENT = {
  title: 'Terms of Service',
  lastUpdated: 'August 16, 2026',
  intro:
    'These Terms of Service ("Terms") constitute a legally binding agreement between you ("you," "user," or "User") and Alizabeth James, an individual doing business as Jesus Interactive ("we," "us," "our," or "Jesus Interactive"), governing your access to and use of the Jesus Interactive mobile application and related services (collectively, the "App" or "Service").\n\nBy downloading, accessing, or using the App, you agree to be bound by these Terms and our Privacy Policy and AI Disclosure & User Acknowledgment (incorporated by reference). If you do not agree, do not use the App.',
  sections: [
    {
      heading: '1. Eligibility',
      body:
        'You must be at least 13 years of age (or the age of digital consent in your jurisdiction) to use the App. By using the App you represent that you meet this requirement and have the legal capacity to enter into these Terms. If you are using the App on behalf of an organization, you represent that you have authority to bind that organization.',
    },
    {
      heading: '2. Description of the Service',
      body:
        'Jesus Interactive is a faith-oriented mobile application that offers: AI-powered conversational features designed to respond in a style inspired by the teachings of Jesus as recorded in the Christian Scriptures; Bible reading and library tools; community features for sharing posts, testimonies, and prayer requests; Sermon Writer and related content-creation tools; and subscription-based premium features.\n\nThe AI is a simulation only. It is not Jesus Christ, not a real person, not divine, and not a source of revelation or pastoral authority. Full details are set out in the separate AI Disclosure & User Acknowledgment, which forms part of these Terms.',
    },
    {
      heading: '3. Account Registration',
      body:
        'Certain features require an account. You agree to: provide accurate, current, and complete information; maintain the security of your login credentials; accept responsibility for all activity under your account; and notify us promptly of any unauthorized use.\n\nWe reserve the right to suspend or terminate accounts that violate these Terms or that we reasonably believe pose a security or legal risk.',
    },
    {
      heading: '4. Subscriptions, Purchases, and Billing',
      body:
        'The App offers free features and optional paid subscriptions (Basic, Pro, Platinum, or other tiers we may introduce) and one-time purchases.\n\nPayment Processing: All payments are processed by Apple (App Store) or Google (Google Play). We do not collect or store your full payment card details.\n\nAuto-Renewal: Subscriptions automatically renew unless you cancel at least 24 hours before the end of the current period through your Apple ID or Google Play account settings.\n\nPricing: Prices are displayed in the App and may vary by region and currency. We reserve the right to change prices with notice as required by the platform.\n\nRefunds: Refund requests are handled according to the refund policies of Apple or Google. We do not control refund decisions.\n\nFree Trials: If a free trial is offered, you will be charged at the end of the trial unless you cancel beforehand.\n\nYour purchase is also subject to the applicable Apple Media Services Terms or Google Play Terms of Service.',
    },
    {
      heading: '5. License to Use the App',
      body:
        'Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to download and use the App on devices you own or control for your personal, non-commercial use.\n\nYou may not: copy, modify, distribute, sell, or lease any part of the App; reverse engineer, decompile, or attempt to extract source code; remove proprietary notices; use the App for any commercial purpose without our prior written consent; or use automated systems (bots, scrapers) to access the Service except as expressly permitted.',
    },
    {
      heading: '6. User Content',
      body:
        '"User Content" means any content you submit, post, or transmit through the App, including chat messages, sermon drafts, community posts, comments, and prayer requests.\n\nYou retain ownership of your User Content. By submitting User Content you grant us a worldwide, non-exclusive, royalty-free, sublicensable license to use, host, store, reproduce, modify, create derivative works from, communicate, and display that content solely for the purposes of operating, improving, and providing the Service.\n\nYou represent and warrant that: you own or have the necessary rights to your User Content; your User Content does not violate any law or third-party rights; and your User Content does not contain malicious code.\n\nWe may remove or disable access to any User Content that we believe violates these Terms or is otherwise objectionable, at our sole discretion.',
    },
    {
      heading: '7. Acceptable Use and Prohibited Conduct',
      body:
        'You agree not to use the App to: violate any applicable law or regulation; infringe intellectual property, privacy, or publicity rights; harass, threaten, defame, or harm others; post content that is pornographic, excessively violent, hateful, or discriminatory; attempt to impersonate any person or entity (including claiming to be Jesus, God, or a spiritual authority); upload viruses, malware, or other harmful code; interfere with or disrupt the Service or servers; attempt to gain unauthorized access to any systems or accounts; use the AI features to generate content intended to deceive others about the nature of the AI; scrape, data-mine, or collect information about other users without consent; or engage in any activity that could damage our reputation or the reputation of the Christian faith as we reasonably determine.\n\nWe reserve the right to investigate and take appropriate action, including suspension or termination of accounts and reporting to law enforcement.',
    },
    {
      heading: '8. AI-Generated Content -- Special Terms',
      body:
        'All AI-generated responses are subject to the AI Disclosure & User Acknowledgment. In addition: AI outputs are provided "as is" for personal reflection, education, and creative assistance only; you are solely responsible for evaluating and verifying any AI-generated content before relying on it; we do not guarantee that AI responses will be theologically accurate, free from error, or consistent with any particular Christian tradition; you may not present AI-generated content as divine revelation, prophetic utterance, or the actual words of Jesus Christ; and you may not use the AI to create content that promotes harm, illegal activity, or theological claims presented as authoritative new revelation.',
    },
    {
      heading: '9. Intellectual Property',
      body:
        'The App, including its design, text, graphics, logos, software, and original content (excluding User Content and third-party Bible text), is owned by us or our licensors and is protected by copyright, trademark, and other laws.\n\nBible text displayed in the App is subject to the copyright and licensing terms of the respective Bible publishers or rights holders. You may not reproduce or distribute substantial portions of copyrighted Bible text outside the App except as permitted by applicable copyright law or the relevant license.\n\n"Jesus Interactive" and related branding are our trademarks. You may not use them without prior written permission.',
    },
    {
      heading: '10. Third-Party Services and Links',
      body:
        'The App may integrate or link to third-party services (AI providers, Bible content providers, payment processors, analytics). Your use of those services is subject to their own terms and privacy policies. We are not responsible for third-party services.',
    },
    {
      heading: '11. Disclaimers',
      body:
        'THE APP AND ALL CONTENT (INCLUDING AI-GENERATED CONTENT) ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND ACCURACY.\n\nWE DO NOT WARRANT THAT: THE APP WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE; AI RESPONSES WILL BE ACCURATE, COMPLETE, OR THEOLOGICALLY CORRECT; ANY DEFECTS WILL BE CORRECTED; OR THE APP IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.\n\nTHE AI IS NOT A SUBSTITUTE FOR SCRIPTURE, PRAYER, THE LOCAL CHURCH, PASTORAL CARE, OR PROFESSIONAL MEDICAL, MENTAL-HEALTH, LEGAL, OR FINANCIAL ADVICE.',
    },
    {
      heading: '12. Limitation of Liability',
      body:
        'TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL WE OR OUR AFFILIATES, OFFICERS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, OR ANY LOSS OF PROFITS, DATA, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF (OR INABILITY TO USE) THE APP, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\nOUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR THE APP SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM OR (B) ONE HUNDRED U.S. DOLLARS (USD $100).\n\nSOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS; IN THOSE CASES OUR LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.',
    },
    {
      heading: '13. Indemnification',
      body:
        'You agree to indemnify, defend, and hold harmless Jesus Interactive and its agents from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys\' fees) arising out of or related to: your use of the App; your User Content; your violation of these Terms; your violation of any third-party rights; or your misuse of AI-generated content.',
    },
    {
      heading: '14. Termination',
      body:
        'We may suspend or terminate your access to the App at any time, with or without notice, for any reason, including violation of these Terms.\n\nYou may stop using the App and delete your account at any time. Upon termination, the license granted to you ends, and Sections that by their nature should survive (including ownership, disclaimers, limitations of liability, and indemnification) will survive.',
    },
    {
      heading: '15. Governing Law and Dispute Resolution',
      body:
        'These Terms are governed by the laws of the State of California, United States, without regard to conflict-of-law principles.\n\nAny dispute arising out of or relating to these Terms or the App shall first be attempted to be resolved through good-faith informal negotiation. If unresolved, the dispute shall be submitted to binding arbitration administered by the American Arbitration Association under its Consumer Arbitration Rules. The arbitration shall take place in Riverside County, California (or another mutually agreed location). Judgment on the award may be entered in any court of competent jurisdiction.\n\nYou and we waive any right to a jury trial and to participate in a class action. Nothing in this section prevents either party from seeking injunctive or other equitable relief in a court of competent jurisdiction for intellectual-property or data-security matters.',
    },
    {
      heading: '16. Changes to These Terms',
      body:
        'We may modify these Terms at any time. We will post the updated Terms in the App and update the "Last Updated" date. Material changes will be highlighted or communicated through the App or by email when appropriate. Your continued use of the App after the effective date of changes constitutes acceptance of the revised Terms. If you do not agree, you must stop using the App.',
    },
    {
      heading: '17. General Provisions',
      body:
        'Entire Agreement: These Terms, together with the Privacy Policy and AI Disclosure & User Acknowledgment, constitute the entire agreement between you and us regarding the App.\n\nSeverability: If any provision is held invalid or unenforceable, the remaining provisions remain in full force.\n\nWaiver: Our failure to enforce any right or provision is not a waiver of that right or provision.\n\nAssignment: You may not assign these Terms without our consent. We may assign them freely.\n\nForce Majeure: We are not liable for delays or failures due to causes beyond our reasonable control.\n\nNotices: We may provide notices via the App, email, or other reasonable means.',
    },
    {
      heading: '18. Contact Information',
      body:
        'For questions about these Terms, please contact:\n\nAlizabeth James, doing business as Jesus Interactive\nCathedral City, California, United States\nEmail: Ajames@jesusinteractive.com\n© 2026 Jesus Interactive',
    },
  ],
  closing:
    'By using Jesus Interactive you acknowledge that you have read, understood, and agree to be bound by these Terms of Service, the Privacy Policy, and the AI Disclosure & User Acknowledgment.',
};

export const PRIVACY_POLICY = {
  title: 'Privacy Policy',
  lastUpdated: 'August 16, 2026',
  effectiveDate: 'August 16, 2026',
  intro:
    'Alizabeth James, an individual doing business as Jesus Interactive ("we," "us," "our," or "Jesus Interactive"), operates the mobile application Jesus Interactive (the "App" or "Service"). This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use the App.\n\nPlease read this Privacy Policy carefully. By accessing or using the App, you agree to the collection and use of information in accordance with this policy. If you do not agree, do not use the App.',
  sections: [
    {
      heading: '1. Information We Collect',
      body:
        'We collect information in the following categories:\n\nA. Information You Provide Directly\n- Account Information: Email address, display name, and password (or authentication credentials) when you create an account.\n- Profile Information: Optional information you choose to provide (e.g., faith tradition preferences, interests).\n- User Content: Messages you send to the AI, sermon drafts you create, community posts, prayer requests, comments, and any other content you submit.\n- Communications: Messages you send to us for support or feedback.\n- Subscription and Purchase Data: Records of your subscription tier and in-app purchases (payment processing is handled by Apple or Google; we do not receive your full payment card details).\n\nB. Information Collected Automatically\n- Device and Usage Data: Device type, operating system version, unique device identifiers, IP address, app version, crash logs, performance data, and general usage statistics (screens viewed, features used, session duration).\n- Log Data: Time and date of access, pages or screens visited, and other diagnostic data.\n- Cookies and Similar Technologies: We may use local storage, cookies, or similar technologies on any associated web components for functionality and analytics.\n\nC. Information from Third Parties\n- Apple App Store / Google Play: Limited subscription and purchase confirmation data necessary to unlock paid features.\n- AI Service Providers: When you use AI features, your message text and limited conversation context are sent to third-party AI providers to generate responses (see Section 3).\n\nWe do not intentionally collect precise location data, contacts, photos, microphone, or camera data unless you explicitly grant permission for a specific feature that requires it.',
    },
    {
      heading: '2. How We Use Your Information',
      body:
        'We use the information we collect to: provide, operate, and maintain the App and its features (including AI chat, Sermon Writer, Bible tools, and Community); process and manage your subscriptions and purchases; personalize your experience (e.g., preferred Bible translation or theme); improve the App, develop new features, and conduct analytics; communicate with you about updates, security alerts, and support; detect, prevent, and address technical issues, fraud, abuse, and violations of our Terms; comply with legal obligations and enforce our rights; and moderate Community content and respond to user reports.',
    },
    {
      heading: '3. AI Features and Third-Party AI Providers',
      body:
        'When you use any AI-powered feature (chat, Sermon Writer, etc.): the text of your prompts and relevant conversation history is transmitted to one or more third-party artificial intelligence providers so that a response can be generated. These providers process the data solely to return a response to us. We configure the service so that your private conversations are not used to train the providers\' foundation models unless you later give separate, explicit opt-in consent (which is never required to use the Service). By using AI features you provide explicit consent to this transmission of your message content to the AI provider(s).\n\nWe will identify the primary AI provider(s) in the App or in an updated version of this Policy when the production provider is finalized. You may choose not to use AI features if you do not wish your messages to be processed by third-party AI services.',
    },
    {
      heading: '4. How We Share Your Information',
      body:
        'We do not sell your personal information.\n\nWe may share information only in these limited circumstances:\n- Service Providers: With vendors who help us operate the App (hosting, analytics, customer support, AI processing, email delivery). These providers are contractually obligated to protect your data and use it only for the services they provide to us.\n- AI Providers: As described in Section 3.\n- Legal Requirements: When required by law, subpoena, court order, or governmental request, or to protect the rights, property, or safety of us, our users, or others.\n- Business Transfers: In connection with a merger, acquisition, reorganization, or sale of assets (your information would remain subject to confidentiality protections).\n- With Your Consent: When you explicitly direct us to share information.\n- Aggregated / De-identified Data: We may share aggregated or de-identified information that cannot reasonably be used to identify you.\n\nCommunity posts and public content you choose to share are visible to other users according to the visibility settings you select.',
    },
    {
      heading: '5. Data Retention',
      body:
        'We retain your information only as long as necessary to provide the Service and fulfill the purposes described in this Policy, unless a longer retention period is required or permitted by law.\n- Account data is retained while your account remains active.\n- Chat history and Sermon Writer content are retained so you can access them; you may delete individual items or request account deletion.\n- After account deletion we will delete or anonymize personal data within a reasonable period, except where we must retain it for legal, security, or legitimate business purposes (e.g., fraud prevention, resolving disputes).',
    },
    {
      heading: '6. Your Rights and Choices',
      body:
        'Depending on your location, you may have rights including: access to the personal data we hold about you; correction of inaccurate data; deletion of your data ("right to be forgotten"); restriction or objection to certain processing; data portability; and withdrawal of consent (where processing is based on consent).\n\nTo exercise these rights, contact us at the email address below. We will respond within the timeframes required by applicable law.\n\nAccount Deletion: You may delete your account from within the App (Settings) or by contacting us. Deletion is permanent and will remove your chat history, saved content, and profile (subject to legal retention requirements).\n\nOpt-Out of Marketing: You can opt out of non-essential communications by following the unsubscribe link or contacting us.\n\nAI Features: You may simply choose not to use AI chat or Sermon Writer features.',
    },
    {
      heading: '7. Children\'s Privacy',
      body:
        'The App is not directed to children under 13 years of age (or the equivalent age of digital consent in your jurisdiction). We do not knowingly collect personal information from children under 13. If we learn that we have collected personal information from a child under 13, we will delete it promptly. If you believe a child has provided us with personal information, please contact us.',
    },
    {
      heading: '8. Data Security',
      body:
        'We implement reasonable administrative, technical, and physical safeguards designed to protect your information. However, no method of transmission over the Internet or electronic storage is 100% secure. We cannot guarantee absolute security.',
    },
    {
      heading: '9. International Users',
      body:
        'The App is operated from the United States. If you access the App from outside the United States, your information may be transferred to, stored, and processed in the United States or other countries where our service providers operate. By using the App you consent to this transfer.\n\nIf you are located in the European Economic Area, United Kingdom, or Switzerland, we process your data in accordance with applicable data-protection laws. Our legal bases for processing include contract performance, legitimate interests, consent, and legal obligations.',
    },
    {
      heading: '10. California Privacy Rights (CCPA/CPRA)',
      body:
        'If you are a California resident, you have additional rights under the California Consumer Privacy Act (as amended by the CPRA), including the right to know, delete, correct, and opt out of the sale or sharing of personal information. We do not sell personal information. To exercise your rights, contact us as described below. We will not discriminate against you for exercising your rights.',
    },
    {
      heading: '11. Third-Party Links and Services',
      body:
        'The App may contain links to third-party websites or services (including Bible text providers). We are not responsible for the privacy practices of those third parties. We encourage you to read their privacy policies.\n\nPayment processing is handled entirely by Apple or Google. Their privacy policies govern the handling of your payment information.',
    },
    {
      heading: '12. Changes to This Privacy Policy',
      body:
        'We may update this Privacy Policy from time to time. We will post the revised Policy in the App and update the "Last Updated" date. Material changes will be communicated through the App or by email when appropriate. Your continued use of the App after the effective date of changes constitutes acceptance of the revised Policy.',
    },
    {
      heading: '13. Contact Us',
      body:
        'If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact:\n\nAlizabeth James, doing business as Jesus Interactive\nCathedral City, California, United States\nEmail: Ajames@jesusinteractive.com\n\nFor privacy-specific requests, please include "Privacy Request" in the subject line and sufficient information for us to verify your identity and respond.',
    },
  ],
};
