import type { Prophecy, ProphecyCategory } from '../types';

// Scholars commonly cite somewhere in the range of 300-400 Old Testament
// passages read as messianic. This list is a substantial, representative
// set organized into four categories -- not an exhaustive catalog -- with
// two "spotlight" entries (Isaiah 53 and Psalm 22 as whole chapters) given
// fuller treatment, since those two carry particular weight in
// conversations with Jewish users specifically. References are
// public-domain (KJV numbering).

export const PROPHECY_CATEGORIES: ProphecyCategory[] = [
  'Birth & Early Life',
  'Ministry & Character',
  'Betrayal, Suffering & Death',
  'Resurrection & Exaltation',
];

export const PROPHECIES: Prophecy[] = [
  // -- Birth & Early Life -----------------------------------------------
  {
    id: 'p1',
    topic: 'Born of a virgin',
    category: 'Birth & Early Life',
    otReference: 'Isaiah 7:14',
    otText: 'A virgin shall conceive, and bear a son, and shall call his name Immanuel.',
    fulfillmentReference: 'Matthew 1:18-23; Luke 1:26-35',
    fulfillmentSummary: 'Mary conceives by the Holy Spirit while a virgin.',
    explanation: 'Matthew quotes this verse directly at Jesus\' birth; Luke independently records the angel Gabriel\'s annunciation to Mary, a virgin betrothed to Joseph -- two separate Gospel traditions converging on the same claim.',
    spotlight: true,
  },
  {
    id: 'p2',
    topic: 'Born in Bethlehem',
    category: 'Birth & Early Life',
    otReference: 'Micah 5:2',
    otText: 'Out of thee shall he come forth unto me that is to be ruler in Israel.',
    fulfillmentReference: 'Matthew 2:1; Luke 2:4-7',
    fulfillmentSummary: 'Jesus is born in Bethlehem of Judea.',
    explanation: 'Micah names the town centuries in advance; both Matthew and Luke -- writing independently, from different sources -- place the birth there, even though Jesus\' family lived in Nazareth.',
    spotlight: true,
  },
  {
    id: 'p3',
    topic: 'Descendant of Abraham',
    category: 'Birth & Early Life',
    otReference: 'Genesis 22:18',
    otText: 'In thy seed shall all the nations of the earth be blessed.',
    fulfillmentReference: 'Matthew 1:1; Galatians 3:16',
    fulfillmentSummary: 'Jesus\' genealogy is traced to Abraham.',
  },
  {
    id: 'p4',
    topic: 'Of the tribe of Judah',
    category: 'Birth & Early Life',
    otReference: 'Genesis 49:10',
    otText: 'The sceptre shall not depart from Judah... until Shiloh come.',
    fulfillmentReference: 'Luke 3:33; Hebrews 7:14',
    fulfillmentSummary: 'Jesus descends from the tribe of Judah.',
  },
  {
    id: 'p5',
    topic: 'Heir to David\'s throne',
    category: 'Birth & Early Life',
    otReference: 'Isaiah 9:7',
    otText: 'Of the increase of his government and peace there shall be no end, upon the throne of David.',
    fulfillmentReference: 'Luke 1:32-33',
    fulfillmentSummary: 'The angel Gabriel tells Mary her son will reign on David\'s throne forever.',
    explanation: 'Both Matthew\'s and Luke\'s genealogies (see the About screen\'s Lineage section) independently connect Jesus to David, satisfying the royal, legal claim to this promise.',
  },

  // -- Ministry & Character -----------------------------------------------
  {
    id: 'p6',
    topic: 'Preceded by a forerunner',
    category: 'Ministry & Character',
    otReference: 'Isaiah 40:3; Malachi 3:1',
    otText: 'The voice of him that crieth in the wilderness, Prepare ye the way of the Lord.',
    fulfillmentReference: 'Matthew 3:1-3; John 1:23',
    fulfillmentSummary: 'John the Baptist prepares the way for Jesus.',
  },
  {
    id: 'p7',
    topic: 'Ministry begins in Galilee',
    category: 'Ministry & Character',
    otReference: 'Isaiah 9:1-2',
    otText: 'The people that walked in darkness have seen a great light.',
    fulfillmentReference: 'Matthew 4:12-16',
    fulfillmentSummary: 'Jesus begins His public ministry in Galilee.',
    explanation: 'A region looked down on by the religious establishment of the day is named, specifically, as where the light would first dawn -- and that is exactly where Jesus\' ministry starts.',
    spotlight: true,
  },
  {
    id: 'p8',
    topic: 'Taught in parables',
    category: 'Ministry & Character',
    otReference: 'Psalm 78:2',
    otText: 'I will open my mouth in a parable: I will utter dark sayings of old.',
    fulfillmentReference: 'Matthew 13:34-35',
    fulfillmentSummary: 'Jesus consistently teaches the crowds in parables.',
  },
  {
    id: 'p9',
    topic: 'Triumphal entry on a donkey',
    category: 'Ministry & Character',
    otReference: 'Zechariah 9:9',
    otText: 'Thy King cometh unto thee... lowly, and riding upon an ass.',
    fulfillmentReference: 'Matthew 21:1-11',
    fulfillmentSummary: 'Jesus enters Jerusalem on a donkey to crowds\' praise.',
    explanation: 'A king riding a donkey rather than a warhorse is a deliberate sign of humility -- Jesus stages this entry knowingly, in view of the whole city, days before His arrest.',
  },

  // -- Betrayal, Suffering & Death -----------------------------------------------
  {
    id: 'isaiah53-spotlight',
    topic: 'The Suffering Servant (Isaiah 53, whole chapter)',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Isaiah 52:13-53:12',
    otText:
      'He was despised and rejected of men; a man of sorrows, and acquainted with grief... he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed... he was brought as a lamb to the slaughter... he was cut off out of the land of the living: for the transgression of my people was he stricken... he made his grave with the wicked, and with the rich in his death... yet it pleased the Lord to bruise him.',
    fulfillmentReference: 'Matthew 27; Mark 15; Luke 23; John 19; 1 Peter 2:24-25',
    fulfillmentSummary: 'The whole arc of Jesus\' unjust suffering, silent submission, substitutionary death, and burial among the wealthy maps onto this chapter as a whole, not just isolated verses.',
    explanation:
      'Isaiah 53 is the single most sustained Old Testament portrait of a suffering, substitutionary Messiah -- written roughly 700 years before the crucifixion. It carries particular weight in conversations with Jewish users specifically, since it sits inside the Hebrew Scriptures themselves (part of the Haftarah readings), independent of the New Testament, describing a servant who suffers for the sins of others, is silent before his accusers, dies among the wicked yet is buried with the rich, and whose suffering "makes many righteous." Different traditions read the "servant" differently (the nation of Israel corporately, a righteous remnant, or an individual Messiah) -- Christian reading holds it as directly, personally fulfilled in Jesus, and the specificity of the details (silence before accusers, burial with the rich despite dying a criminal\'s death, bearing others\' guilt) is why this chapter carries such weight.',
    spotlight: true,
  },
  {
    id: 'psalm22-spotlight',
    topic: 'Psalm 22 (whole psalm)',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Psalm 22:1-31',
    otText:
      'My God, my God, why hast thou forsaken me?... I am poured out like water, and all my bones are out of joint... they pierced my hands and my feet... they part my garments among them, and cast lots upon my vesture... I will declare thy name unto my brethren... all the ends of the world shall remember and turn unto the Lord.',
    fulfillmentReference: 'Matthew 27:35, 46; John 19:23-24, 28-30',
    fulfillmentSummary: 'Jesus quotes this psalm\'s opening line from the cross; the piercing, the mockery, and the soldiers gambling for His garments all match, and the psalm turns from anguish to worldwide worship by its end.',
    explanation:
      'David wrote this roughly a thousand years before crucifixion existed as a Roman execution method, yet describes pierced hands and feet, exposed and dislocated bones, mockery matching the exact words used at the cross (Matthew 27:39-43 echoes verses 7-8), and soldiers dividing and casting lots for clothing. Like Isaiah 53, it is part of the Hebrew Scriptures read on its own terms, which is why it carries special weight in conversation with Jewish users -- the psalm itself moves from desolation ("why hast thou forsaken me") to a declaration that "all the ends of the world shall... turn unto the Lord," a shape Christians read as anguish giving way to resurrection and global gospel proclamation.',
    spotlight: true,
  },
  {
    id: 'p10',
    topic: 'Betrayed by a close friend',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Psalm 41:9',
    otText: 'Mine own familiar friend... hath lifted up his heel against me.',
    fulfillmentReference: 'Matthew 26:14-16, 47-50',
    fulfillmentSummary: 'Judas, one of the twelve, betrays Jesus.',
  },
  {
    id: 'p11',
    topic: 'Sold for thirty pieces of silver',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Zechariah 11:12',
    otText: 'So they weighed for my price thirty pieces of silver.',
    fulfillmentReference: 'Matthew 26:15',
    fulfillmentSummary: 'The chief priests pay Judas exactly that amount.',
    spotlight: true,
  },
  {
    id: 'p12',
    topic: 'Price thrown down in the temple, used for a potter\'s field',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Zechariah 11:13',
    otText: 'Cast it unto the potter... I took the thirty pieces of silver.',
    fulfillmentReference: 'Matthew 27:5-7',
    fulfillmentSummary: 'Judas throws the silver into the temple; it buys the potter\'s field.',
  },
  {
    id: 'p13',
    topic: 'Forsaken by His disciples',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Zechariah 13:7',
    otText: 'Smite the shepherd, and the sheep shall be scattered.',
    fulfillmentReference: 'Matthew 26:31, 56',
    fulfillmentSummary: 'The disciples flee after Jesus\' arrest.',
  },
  {
    id: 'p14',
    topic: 'Silent before His accusers',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Isaiah 53:7',
    otText: 'He is brought as a lamb to the slaughter... he openeth not his mouth.',
    fulfillmentReference: 'Matthew 27:12-14',
    fulfillmentSummary: 'Jesus gives no answer before Pilate and the chief priests.',
  },
  {
    id: 'p15',
    topic: 'Struck and spat upon',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Isaiah 50:6',
    otText: 'I hid not my face from shame and spitting.',
    fulfillmentReference: 'Matthew 26:67; 27:30',
    fulfillmentSummary: 'Jesus is struck, mocked, and spat upon before the crucifixion.',
  },
  {
    id: 'p16',
    topic: 'Hands and feet pierced',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Psalm 22:16',
    otText: 'They pierced my hands and my feet.',
    fulfillmentReference: 'Luke 23:33; John 20:25',
    fulfillmentSummary: 'Jesus is crucified, nailed through hands and feet.',
    spotlight: true,
  },
  {
    id: 'p17',
    topic: 'Numbered with transgressors',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Isaiah 53:12',
    otText: 'He was numbered with the transgressors.',
    fulfillmentReference: 'Matthew 27:38; Mark 15:27-28',
    fulfillmentSummary: 'Jesus is crucified between two criminals.',
  },
  {
    id: 'p18',
    topic: 'Mocked and ridiculed on the cross',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Psalm 22:7-8',
    otText: 'They shoot out the lip, they shake the head... let him deliver him.',
    fulfillmentReference: 'Matthew 27:39-43',
    fulfillmentSummary: 'Passersby and leaders mock Jesus on the cross in almost these exact words.',
  },
  {
    id: 'p19',
    topic: 'Prayed for His persecutors',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Isaiah 53:12',
    otText: 'He made intercession for the transgressors.',
    fulfillmentReference: 'Luke 23:34',
    fulfillmentSummary: '"Father, forgive them, for they know not what they do."',
  },
  {
    id: 'p20',
    topic: 'Garments divided by lot',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Psalm 22:18',
    otText: 'They part my garments among them, and cast lots upon my vesture.',
    fulfillmentReference: 'Matthew 27:35; John 19:23-24',
    fulfillmentSummary: 'Soldiers gamble for Jesus\' clothing at the foot of the cross.',
    spotlight: true,
  },
  {
    id: 'p21',
    topic: 'Not a bone broken',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Psalm 34:20; Exodus 12:46',
    otText: 'He keepeth all his bones: not one of them is broken.',
    fulfillmentReference: 'John 19:33-36',
    fulfillmentSummary: 'Soldiers break the other victims\' legs but not Jesus\', who is already dead.',
  },
  {
    id: 'p22',
    topic: 'His side pierced',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Zechariah 12:10',
    otText: 'They shall look upon me whom they have pierced.',
    fulfillmentReference: 'John 19:34, 37',
    fulfillmentSummary: 'A soldier pierces Jesus\' side with a spear.',
  },
  {
    id: 'p23',
    topic: 'Darkness at His death',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Amos 8:9',
    otText: 'I will cause the sun to go down at noon, and I will darken the earth.',
    fulfillmentReference: 'Matthew 27:45',
    fulfillmentSummary: 'Darkness covers the land from the sixth to the ninth hour.',
  },
  {
    id: 'p24',
    topic: 'Buried with the rich',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Isaiah 53:9',
    otText: 'He made his grave with the wicked, and with the rich in his death.',
    fulfillmentReference: 'Matthew 27:57-60',
    fulfillmentSummary: 'Jesus is buried in the tomb of Joseph of Arimathea, a rich man.',
  },
  {
    id: 'p27',
    topic: 'Cut off for the people, not Himself',
    category: 'Betrayal, Suffering & Death',
    otReference: 'Daniel 9:26',
    otText: 'Messiah [shall] be cut off, but not for himself.',
    fulfillmentReference: 'Fulfilled at the crucifixion',
    fulfillmentSummary: 'Jesus dies as a substitutionary sacrifice, not for His own sin.',
  },

  // -- Resurrection & Exaltation -----------------------------------------------
  {
    id: 'p25',
    topic: 'Resurrection from the dead',
    category: 'Resurrection & Exaltation',
    otReference: 'Psalm 16:10; Isaiah 53:10-11',
    otText: 'Thou wilt not leave my soul in hell, neither wilt thou suffer thine Holy One to see corruption.',
    fulfillmentReference: 'Matthew 28:1-10; Acts 2:31',
    fulfillmentSummary: 'Jesus rises bodily on the third day.',
    explanation: 'Peter directly cites this psalm in his first recorded sermon (Acts 2) as proof of the resurrection, arguing David himself remained in the grave, so the psalm must point beyond him.',
    spotlight: true,
  },
  {
    id: 'p26',
    topic: 'Ascension to the Father',
    category: 'Resurrection & Exaltation',
    otReference: 'Psalm 68:18',
    otText: 'Thou hast ascended on high, thou hast led captivity captive.',
    fulfillmentReference: 'Acts 1:9-11',
    fulfillmentSummary: 'Jesus is taken up into heaven before His disciples.',
  },
];

export function prophecyCountLabel(): string {
  return `${PROPHECIES.length} shown here of the roughly 300-400 messianic passages scholars commonly reference`;
}
