// Bible Crossword -- one of the 9 Jesus Interactive Games Hub tiles.
// Deliberately colorful/playful (Words With Friends style tiles), not
// the app's usual navy/gold devotional look -- see GamesHubScreen.tsx's
// own comment on why this whole feature breaks from that palette.
//
// Puzzles are generated by services/crosswordPuzzle.ts from the shared
// WEB Bible content library -- every answer and clue traces back to a
// real verse, nothing hand-authored per puzzle.
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import Colors from '../../theme/colors';
import DraggableScrollbar from '../../components/DraggableScrollbar';
import { GAMES_CATALOG, type Difficulty } from '../../data/gamesCatalog';
import { generateCrossword, getRandomCrosswordSeed, type CrosswordPuzzle, type PlacedCrosswordWord } from '../../services/crosswordPuzzle';

const ACCENT = GAMES_CATALOG.find((g) => g.id === 'GameCrossword')!.color;

type CellWords = { across?: PlacedCrosswordWord; down?: PlacedCrosswordWord };

function buildWordLookup(puzzle: CrosswordPuzzle): Map<string, CellWords> {
  const lookup = new Map<string, CellWords>();
  for (const word of puzzle.words) {
    const [dRow, dCol] = word.direction === 'across' ? [0, 1] : [1, 0];
    for (let i = 0; i < word.answer.length; i++) {
      const key = `${word.row + dRow * i},${word.col + dCol * i}`;
      const entry = lookup.get(key) ?? {};
      entry[word.direction] = word;
      lookup.set(key, entry);
    }
  }
  return lookup;
}

export default function CrosswordScreen() {
  const [difficulty, setDifficulty] = useState<Difficulty>('easy');
  const [seed, setSeed] = useState(() => getRandomCrosswordSeed());
  const puzzle = useMemo(() => generateCrossword(seed, difficulty), [seed, difficulty]);
  const wordLookup = useMemo(() => buildWordLookup(puzzle), [puzzle]);
  // Cell -> clue number, for the small number label drawn in a word's
  // starting cell -- precomputed once per puzzle rather than scanning
  // puzzle.words on every one of the up to 225 cell renders.
  const numberLookup = useMemo(() => {
    const map = new Map<string, number>();
    for (const w of puzzle.words) map.set(`${w.row},${w.col}`, w.number);
    return map;
  }, [puzzle]);

  const [guesses, setGuesses] = useState<(string | null)[][]>(() =>
    puzzle.solution.map((row) => row.map((cell) => (cell ? '' : null)))
  );
  const [selected, setSelected] = useState<{ row: number; col: number } | null>(null);
  const [direction, setDirection] = useState<'across' | 'down'>('across');
  const [checkedWrong, setCheckedWrong] = useState<Set<string>>(new Set());
  const [solved, setSolved] = useState(false);
  const [showAnswers, setShowAnswers] = useState(false);

  const inputRefs = useRef<Map<string, TextInput | null>>(new Map());

  useEffect(() => {
    setGuesses(puzzle.solution.map((row) => row.map((cell) => (cell ? '' : null))));
    setSelected(null);
    setCheckedWrong(new Set());
    setSolved(false);
    setShowAnswers(false);
    inputRefs.current.clear();
  }, [puzzle]);

  const wordAt = (row: number, col: number, dir: 'across' | 'down') => wordLookup.get(`${row},${col}`)?.[dir];

  const activeWord = selected ? wordAt(selected.row, selected.col, direction) : undefined;
  const activeWordCells = useMemo(() => {
    if (!activeWord) return new Set<string>();
    const [dRow, dCol] = activeWord.direction === 'across' ? [0, 1] : [1, 0];
    const cells = new Set<string>();
    for (let i = 0; i < activeWord.answer.length; i++) {
      cells.add(`${activeWord.row + dRow * i},${activeWord.col + dCol * i}`);
    }
    return cells;
  }, [activeWord]);

  // Deferred one tick -- calling .focus() on the next cell synchronously,
  // in the same tick as the state update that changes what's rendered,
  // is a known React Native gotcha for a grid of single-character
  // TextInputs: the focus call can silently lose the race against the
  // in-flight re-render, especially once a couple of state updates are
  // already queued up (reported as "only the first couple of letters
  // ever get typed" -- not any one specific cell). Letting the current
  // commit finish first makes each focus call land on a settled tree.
  const focusCell = (row: number, col: number) => {
    setTimeout(() => {
      inputRefs.current.get(`${row},${col}`)?.focus();
    }, 0);
  };

  const selectCell = (row: number, col: number) => {
    if (selected && selected.row === row && selected.col === col) {
      const other: 'across' | 'down' = direction === 'across' ? 'down' : 'across';
      if (wordAt(row, col, other)) setDirection(other);
    } else {
      setSelected({ row, col });
      const preferred = wordAt(row, col, direction) ? direction : wordAt(row, col, 'across') ? 'across' : 'down';
      setDirection(preferred);
    }
    focusCell(row, col);
  };

  const checkSolved = (grid: (string | null)[][]) => {
    for (let r = 0; r < puzzle.size; r++) {
      for (let c = 0; c < puzzle.size; c++) {
        const solutionLetter = puzzle.solution[r][c];
        if (solutionLetter && grid[r][c] !== solutionLetter) return false;
      }
    }
    return true;
  };

  const handleChangeText = (row: number, col: number, text: string) => {
    const letter = text.replace(/[^a-zA-Z]/g, '').slice(-1).toUpperCase();
    setGuesses((prev) => {
      const next = prev.map((r) => r.slice());
      next[row][col] = letter;
      if (checkSolved(next)) setSolved(true);
      return next;
    });
    setCheckedWrong(new Set());
    if (!letter) return;
    const word = wordAt(row, col, direction);
    if (!word) return;
    const [dRow, dCol] = word.direction === 'across' ? [0, 1] : [1, 0];
    const indexInWord = word.direction === 'across' ? col - word.col : row - word.row;
    if (indexInWord < word.answer.length - 1) {
      const nextRow = row + dRow;
      const nextCol = col + dCol;
      setSelected({ row: nextRow, col: nextCol });
      focusCell(nextRow, nextCol);
    }
  };

  const handleKeyPress = (row: number, col: number, key: string) => {
    if (key !== 'Backspace' || guesses[row][col]) return;
    const word = wordAt(row, col, direction);
    if (!word) return;
    const [dRow, dCol] = word.direction === 'across' ? [0, 1] : [1, 0];
    const indexInWord = word.direction === 'across' ? col - word.col : row - word.row;
    if (indexInWord > 0) {
      const prevRow = row - dRow;
      const prevCol = col - dCol;
      setSelected({ row: prevRow, col: prevCol });
      focusCell(prevRow, prevCol);
    }
  };

  const jumpToWord = (word: PlacedCrosswordWord) => {
    setSelected({ row: word.row, col: word.col });
    setDirection(word.direction);
    focusCell(word.row, word.col);
  };

  const handleCheck = () => {
    const wrong = new Set<string>();
    for (let r = 0; r < puzzle.size; r++) {
      for (let c = 0; c < puzzle.size; c++) {
        const solutionLetter = puzzle.solution[r][c];
        if (solutionLetter && guesses[r][c] && guesses[r][c] !== solutionLetter) wrong.add(`${r},${c}`);
      }
    }
    setCheckedWrong(wrong);
  };

  const newPuzzle = () => setSeed(getRandomCrosswordSeed());

  const acrossWords = puzzle.words.filter((w) => w.direction === 'across');
  const downWords = puzzle.words.filter((w) => w.direction === 'down');

  const scrollRef = useRef<ScrollView>(null);
  const [scrollOffset, setScrollOffset] = useState(0);
  const [contentHeight, setContentHeight] = useState(0);
  const [viewportHeight, setViewportHeight] = useState(0);
  const [scrollbarDragging, setScrollbarDragging] = useState(false);

  const cellSize = 22;

  return (
    <SafeAreaView style={styles.safeArea} edges={['bottom', 'left', 'right']}>
      <View style={[styles.header, { backgroundColor: ACCENT }]}>
        <Text style={styles.headerTitle}>Bible Crossword</Text>
        <View style={styles.difficultyRow}>
          {(['easy', 'medium', 'hard'] as Difficulty[]).map((d) => (
            <TouchableOpacity
              key={d}
              style={[styles.difficultyChip, difficulty === d && styles.difficultyChipActive]}
              onPress={() => setDifficulty(d)}
            >
              <Text style={[styles.difficultyChipText, difficulty === d && styles.difficultyChipTextActive]}>
                {d[0].toUpperCase() + d.slice(1)}
              </Text>
            </TouchableOpacity>
          ))}
        </View>
        <Text style={styles.instructions}>Tap a square, then type to fill in the answer. Tap again to switch across/down.</Text>
      </View>

      {solved && (
        <View style={styles.solvedBanner}>
          <Ionicons name="sparkles" size={18} color={Colors.white} />
          <Text style={styles.solvedBannerText}>Solved! Well done.</Text>
        </View>
      )}

      {activeWord && selected && (
        <View style={styles.clueBar}>
          <Text style={styles.clueBarNumber}>{activeWord.number}{activeWord.direction === 'across' ? 'A' : 'D'}</Text>
          <Text style={styles.clueBarText} numberOfLines={2}>{activeWord.clue}</Text>
          {/* Explicit toggle, not just "tap the same square again" --
              that gesture is ambiguous the instant a square belongs to
              both an across and a down word, which is every
              intersection in the grid. Only shown when the OTHER
              direction actually has a word here at all. */}
          {wordAt(selected.row, selected.col, direction === 'across' ? 'down' : 'across') && (
            <TouchableOpacity
              style={styles.directionToggle}
              onPress={() => setDirection((d) => (d === 'across' ? 'down' : 'across'))}
            >
              <Ionicons name="swap-vertical" size={14} color={ACCENT} />
              <Text style={[styles.directionToggleText, { color: ACCENT }]}>
                {direction === 'across' ? 'Down' : 'Across'}
              </Text>
            </TouchableOpacity>
          )}
        </View>
      )}

      <View style={{ flex: 1 }}>
        <ScrollView
          ref={scrollRef}
          contentContainerStyle={styles.content}
          showsVerticalScrollIndicator={false}
          onLayout={({ nativeEvent }) => setViewportHeight(nativeEvent.layout.height)}
          onContentSizeChange={(_w, h) => setContentHeight(h)}
          onScroll={({ nativeEvent }) => setScrollOffset(nativeEvent.contentOffset.y)}
          scrollEventThrottle={16}
          scrollEnabled={!scrollbarDragging}
        >
          <View style={styles.grid}>
            {puzzle.solution.map((row, r) => (
              <View key={r} style={styles.gridRow}>
                {row.map((solutionLetter, c) => {
                  if (!solutionLetter) return <View key={c} style={{ width: cellSize, height: cellSize }} />;
                  const key = `${r},${c}`;
                  const isSelected = selected?.row === r && selected?.col === c;
                  const isActiveWord = activeWordCells.has(key);
                  const isWrong = checkedWrong.has(key);
                  const number = numberLookup.get(key);
                  return (
                    <TouchableOpacity
                      key={c}
                      activeOpacity={0.8}
                      onPress={() => selectCell(r, c)}
                      style={[
                        styles.cell,
                        { width: cellSize, height: cellSize },
                        isActiveWord && styles.cellInWord,
                        isSelected && [styles.cellSelected, { borderColor: ACCENT }],
                        isWrong && styles.cellWrong,
                      ]}
                    >
                      {!!number && <Text style={styles.cellNumber}>{number}</Text>}
                      <TextInput
                        ref={(ref) => {
                          if (ref) inputRefs.current.set(key, ref);
                        }}
                        // pointerEvents="none" -- this input fully covers
                        // the cell (100% width/height), so without this it
                        // silently wins every tap for its own native
                        // focus, and the wrapping TouchableOpacity's
                        // onPress (selectCell, which is what actually
                        // decides across vs. down) never fires. The cell
                        // still becomes focused -- selectCell ends with an
                        // explicit ref.focus() call -- just via that
                        // programmatic call instead of the tap directly,
                        // so the outer TouchableOpacity is the only thing
                        // that owns tap handling now.
                        pointerEvents="none"
                        style={styles.cellInput}
                        value={guesses[r][c] ?? ''}
                        maxLength={1}
                        autoCapitalize="characters"
                        autoCorrect={false}
                        onChangeText={(text) => handleChangeText(r, c, text)}
                        onKeyPress={({ nativeEvent }) => handleKeyPress(r, c, nativeEvent.key)}
                        onFocus={() => setSelected({ row: r, col: c })}
                      />
                    </TouchableOpacity>
                  );
                })}
              </View>
            ))}
          </View>

          <View style={styles.actionsRow}>
            <TouchableOpacity style={[styles.actionButton, { backgroundColor: ACCENT }]} onPress={handleCheck}>
              <Text style={styles.actionButtonText}>Check</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.actionButtonOutline} onPress={newPuzzle}>
              <Text style={[styles.actionButtonOutlineText, { color: ACCENT }]}>New Puzzle</Text>
            </TouchableOpacity>
          </View>

          <TouchableOpacity style={styles.showAnswersRow} onPress={() => setShowAnswers((v) => !v)}>
            <Ionicons name={showAnswers ? 'eye-off-outline' : 'eye-outline'} size={16} color={ACCENT} />
            <Text style={[styles.showAnswersText, { color: ACCENT }]}>
              {showAnswers ? 'Hide answers' : 'Show answers'}
            </Text>
          </TouchableOpacity>

          <View style={styles.cluesSection}>
            <Text style={styles.cluesSectionTitle}>Across</Text>
            {acrossWords.map((w) => (
              <TouchableOpacity key={`a-${w.number}`} style={styles.clueRow} onPress={() => jumpToWord(w)}>
                <Text style={styles.clueRowNumber}>{w.number}.</Text>
                <Text style={styles.clueRowText} numberOfLines={2}>{w.clue}</Text>
                {showAnswers && <Text style={[styles.clueRowAnswer, { color: ACCENT }]}>{w.answer}</Text>}
              </TouchableOpacity>
            ))}
            <Text style={[styles.cluesSectionTitle, { marginTop: 16 }]}>Down</Text>
            {downWords.map((w) => (
              <TouchableOpacity key={`d-${w.number}`} style={styles.clueRow} onPress={() => jumpToWord(w)}>
                <Text style={styles.clueRowNumber}>{w.number}.</Text>
                <Text style={styles.clueRowText} numberOfLines={2}>{w.clue}</Text>
                {showAnswers && <Text style={[styles.clueRowAnswer, { color: ACCENT }]}>{w.answer}</Text>}
              </TouchableOpacity>
            ))}
          </View>
        </ScrollView>
        <DraggableScrollbar
          contentHeight={contentHeight}
          viewportHeight={viewportHeight}
          scrollOffset={scrollOffset}
          onScrollTo={(offset) => {
            scrollRef.current?.scrollTo({ y: offset, animated: false });
            setScrollOffset(offset);
          }}
          onDragStart={() => setScrollbarDragging(true)}
          onDragEnd={() => setScrollbarDragging(false)}
          thumbColor={ACCENT}
        />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFF6ED' },
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 14 },
  headerTitle: { fontSize: 20, fontWeight: '800', color: Colors.white },
  difficultyRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
  difficultyChip: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.25)' },
  difficultyChipActive: { backgroundColor: Colors.white },
  difficultyChipText: { fontSize: 12.5, fontWeight: '700', color: Colors.white },
  difficultyChipTextActive: { color: ACCENT },
  instructions: { fontSize: 12, color: 'rgba(255,255,255,0.9)', marginTop: 10, lineHeight: 16 },
  solvedBanner: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    backgroundColor: '#38B000', paddingVertical: 10,
  },
  solvedBannerText: { color: Colors.white, fontWeight: '800', fontSize: 14 },
  clueBar: {
    flexDirection: 'row', alignItems: 'flex-start', gap: 8,
    backgroundColor: '#FFE8D6', paddingHorizontal: 16, paddingVertical: 10,
  },
  clueBarNumber: { fontSize: 13, fontWeight: '800', color: ACCENT },
  clueBarText: { flex: 1, fontSize: 13, color: '#2E1D0F', fontWeight: '600' },
  directionToggle: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 4, backgroundColor: Colors.white, borderRadius: 12 },
  directionToggleText: { fontSize: 12, fontWeight: '800' },
  showAnswersRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 14 },
  showAnswersText: { fontSize: 13, fontWeight: '700' },
  content: { alignItems: 'center', paddingVertical: 16, paddingBottom: 40 },
  grid: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 6, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 6, elevation: 2 },
  gridRow: { flexDirection: 'row' },
  // No margin here -- the blocked/spacer cells (plain View, same
  // cellSize) don't get one either, so an active cell with its own
  // margin was a slightly bigger box than a blocked one in the same
  // row, and every row's mix of active/blocked cells drifted the
  // columns out of alignment by a fraction of a pixel, compounding
  // across the grid. Border-only separation keeps every cell exactly
  // cellSize x cellSize regardless of whether it's active or blocked.
  cell: {
    borderWidth: 1.5, borderColor: '#8A6E4E', backgroundColor: '#FFFDF8',
    alignItems: 'center', justifyContent: 'center', borderRadius: 3,
  },
  cellInWord: { backgroundColor: '#F5C9A0' },
  cellSelected: { backgroundColor: '#FFD166', borderWidth: 2, borderColor: '#4A3212' },
  cellWrong: { backgroundColor: '#FFC2C2' },
  cellNumber: { position: 'absolute', top: 1, left: 2, fontSize: 7, fontWeight: '800', color: '#4A3212' },
  cellInput: {
    width: '100%', height: '100%', textAlign: 'center', fontSize: 13, fontWeight: '800',
    color: '#1C1006', padding: 0,
  },
  actionsRow: { flexDirection: 'row', gap: 12, marginTop: 18, paddingHorizontal: 20, width: '100%' },
  actionButton: { flex: 1, borderRadius: 22, paddingVertical: 12, alignItems: 'center' },
  actionButtonText: { color: Colors.white, fontWeight: '800', fontSize: 14 },
  actionButtonOutline: { flex: 1, borderRadius: 22, paddingVertical: 12, alignItems: 'center', borderWidth: 2, borderColor: ACCENT },
  actionButtonOutlineText: { fontWeight: '800', fontSize: 14 },
  cluesSection: { width: '100%', paddingHorizontal: 20, marginTop: 24 },
  cluesSectionTitle: { fontSize: 15, fontWeight: '800', color: ACCENT, marginBottom: 8 },
  clueRow: { flexDirection: 'row', gap: 8, paddingVertical: 6, alignItems: 'flex-start' },
  clueRowNumber: { fontSize: 13, fontWeight: '800', color: '#4A3212', width: 24 },
  clueRowText: { flex: 1, fontSize: 13, color: '#1C1006' },
  clueRowAnswer: { fontSize: 13, fontWeight: '800', marginLeft: 8 },
});
